# Generated by Django 5.0.4 on 2024-04-16 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='photo',
            field=models.ImageField(blank=True, upload_to='fotos'),
        ),
    ]
