# Generated by Django 5.0.4 on 2024-04-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_carousel_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
