# Generated by Django 5.0.4 on 2024-04-17 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_carousel_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='fotos')),
                ('text', models.CharField(max_length=1000)),
                ('active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2024, 4, 17, 9, 0, 57, 288937))),
            ],
        ),
        migrations.AddField(
            model_name='carousel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 17, 9, 0, 57, 288937)),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
