# Generated by Django 5.0.4 on 2024-04-17 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_about_carousel_date_alter_carousel_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.CharField(default='null', max_length=15),
        ),
        migrations.AlterField(
            model_name='about',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 17, 9, 36, 28, 827116)),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 17, 9, 36, 28, 827116)),
        ),
    ]
