# Generated by Django 5.0.4 on 2024-04-17 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_about_title_alter_about_date_alter_carousel_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank='False', upload_to='fotos')),
                ('title', models.CharField(default='null', max_length=15)),
                ('text', models.CharField(max_length=1000)),
                ('active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2024, 4, 17, 10, 31, 52, 45040))),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 17, 10, 31, 52, 45040)),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 17, 10, 31, 52, 45040)),
        ),
    ]
